name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests with coverage
      working-directory: ./backend/src
      run: |
        coverage run --source=./ -m pytest
        coverage report

      env:
        SECRET_KEY: 123
        DEBUG: 1
        ALLOWED_HOSTS: localhost
        GITHUB_BASE_API_URL: https://api.github.com
        SUPPORTED_SEARCH_TYPES: users,repositories,issues
        REDIS_URL: redis://localhost:6379/0
        DB_NAME: github_actions
        DB_USER_NAME: postgres
        DB_USER_PASSWORD: postgres
        DB_HOST: localhost